# Generated by Django 2.0.13 on 2020-01-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='isFinish',
        ),
    ]
